services:
  lobos:
    restart: on-failure
    image: ghcr.io/tudemaha/lobos:latest
    environment:
      - DB_URL=jdbc:mysql://<host>:<port>/<database>
      - DB_USERNAME=<username>
      - DB_PASSWORD=<password>
      - JWT_SECRET=<secret>
    ports:
      - 127.0.0.1:8080:8080