spring.application.name=lobos
spring.mvc.hiddenmethod.filter.enabled=true

spring.ai.mcp.server.name=lobos-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.protocol=streamable

spring.datasource.url=jdbc:mysql://192.168.100.190:3234/lobos
spring.datasource.username=tudemaha
spring.datasource.password=***REDACTED-DB-PASSWORD***
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=***REDACTED-JWT-SECRET***