spring.application.name=lobos

spring.datasource.url=jdbc:mysql://192.168.100.190:3234/lobos
spring.datasource.username=tudemaha
spring.datasource.password=maha1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=dkfljalskfjaslfjeiojfojfsdf0ofw0fio2fn3o